### ISSUE TITLE
why is the prepare_data file reading only 2 parameters from the hpo meta datasets?

### ISSUE THREAD

**Issue by vamp-ire-tap** [boschresearch/MetaBO#2]
unfortunately it is not clear as to why in the prepare_data file, only 2 parameters are read:
param_nos_to_extract = [3, 4] for svm meta data
param_nos_to_extract = [0, 1] for adaboost meta data

Could you please comment about this, and also is this related to 'D' in the paper, where it is said that HPO problems are 2D?

**Comment by michaelvolpp** [comment]
Hi vamp-ire-tap!

Thank you for your question. You are right, as stated in the paper, we create 2D HPO problems from the available data: for the SVM's we vary the RBF-kernel parameter and the penalty parameter (corresponding to parameter numbers 3 and 4 in the dataset) and for AdaBoost we vary the number of product terms and the number of iterations (corresponding to parameter numbers 0 and 1 in the dataset).

Best,
Michael
