### ISSUE TITLE
can the actions be repeated in the eval setting?

### ISSUE THREAD

**Issue by vamp-ire-tap** [boschresearch/MetaBO#3]
could someone please let me know if the actions in the 'svm_hpo' environment are actually stored with the transitions: 
transitions = Transition(*zip(*br.memory.copy())) #line number 151; /MetaBO/metabo/eval/evaluate.py 

one can see below that actions are being repeated, which causes two confusing questions: 
1) are these actions the index of the hyperparameter configuration being tried? 
2) why is the model repeating the action, as in rerunning the hpo configuration? 

when i print out the actions for the 'svm_hpo' environment: 
action=(array(117), array(120), array(129), array(123), array(118), array(122), array(121), array(122), array(121), array(121), array(122), array(121), array(121), array(121), array(122), array(121), array(121), array(121), array(122), array(121), array(117), array(120), array(126), array(118), array(119), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(118), array(117), array(118), array(119), array(120), array(121), array(122), array(127), array(125), array(128), array(129), array(122), array(127), array(122), array(129), array(127), array(123), array(127), array(122), array(127), array(127), array(117), array(120), array(129), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(119), array(117), array(119), array(121), array(129), array(118), array(123), array(120), array(119), array(119), array(120), array(119), array(119), array(119), array(119), array(119), array(118), array(119), array(120), array(119), array(119), array(117), array(119), array(122), array(126), array(118), array(121), array(123), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(120), array(126), array(118), array(123), array(127), array(117), array(117), array(118), array(117), array(117), array(117), array(117), array(119), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(120), array(127), array(124), array(123), array(126), array(122), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(124), array(117), array(119), array(127), array(123), array(118), array(128), array(121), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(119), array(122), array(127), array(121), array(122), array(123), array(122), array(121), array(122), array(122), array(121), array(122), array(122), array(121), array(122), array(122), array(122), array(121), array(122), array(117), array(118), array(119), array(120), array(121), array(122), array(127), array(129), array(125), array(126), array(128), array(124), array(123), array(117), array(117), array(117), array(117), array(117), array(118), array(117), array(117), array(120), array(127), array(119), array(120), array(120), array(120), array(123), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(120), array(117), array(118), array(119), array(120), array(121), array(121), array(121), array(121), array(122), array(121), array(127), array(121), array(121), array(121), array(121), array(121), array(121), array(121), array(121), array(121), array(117), array(122), array(123), array(119), array(118), array(128), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(117), array(119), array(120), array(120), array(119), array(120), array(127), array(128), array(120), array(119), array(120), array(119), array(120), array(123), array(119), array(120), array(120), array(119), array(120), array(120))

**Comment by vamp-ire-tap** [comment]
Could someone please answer the question posted above?

**Comment by michaelvolpp** [comment]
Hello vamp-ire-tap!

As you can see from the definition of `Transition` in metabo/ppo/batchrecorder.py, l. 35, the actions are part of the transition: `Transition = namedlist("Transition", ["state", "action", "reward", "value", "new", "tdlamret", "adv"])`.

Regarding you questions:
1) Yes, the actions correspond to the indices of the parameter configurations.
2) It is not unusual to query the objective function multiple time at the same parameter configuration after BO-convergence.

Best,
Michael

**Comment by vamp-ire-tap** [comment]
okay great, thanks a bunch!
